  
# Basic options 
title: Malungisa Mndzebele's website
author: Malungisa Mndzebele
email: mndzma01@luther.edu
description: This site contains information about Malungisa.
github_username: Malungisa

theme: jekyll-theme-cayman
